### ISSUE TITLE
webpack bundle: Cannot find module './jsom/spo/1033/initstrings.debug.js' 

### ISSUE THREAD

**Issue by SPWizard01** [koltyakov/sp-jsom-node#6]
Whenever i run a bundle created with webpack that includes this library and does something with SharePoint i get this error:
UnhandledPromiseRejectionWarning: Error: Cannot find module './jsom/spo/1033/initstrings.debug.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Function.require (internal/modules/cjs/helpers.js:22:18)
    at eval (webpack:///./node_modules/sp-jsom-node/dist/JsomNode.js?:158:37)
    at Array.forEach (<anonymous>)
    at eval (webpack:///./node_modules/sp-jsom-node/dist/JsomNode.js?:149:42)
    at Array.forEach (<anonymous>)
    at JsomNode.loadScripts (webpack:///./node_modules/sp-jsom-node/dist/JsomNode.js?:148:14)
    at JsomNode.init (webpack:///./node_modules/sp-jsom-node/dist/JsomNode.js?:50:14)

i am guessing this is due to specific "importing", can this be somehow worked around?

**Comment by SPWizard01** [comment]
found it in the examples, CopyWebpackPlugin Is the answer.
